
global:
  scrape_interval:  5s
scrape_configs:
  - job_name: prometheus
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['person-service:8080']
        labels:
          instance: person-service-1
          application: person-service
      - targets: ['person-client-service:8081']
        labels:
          instance: person-client-service-1
          application: person-client-service
