server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  metrics:
    export:
      prometheus:
        enabled: true
person:
  backend:
    host: localhost
    httpPort: 8080
    rsocPort: 9080
