{
 "title": "Spring Boot 2.3 Monitor",
 "description": "Dashboard for Spring Boot-2.3",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  { "title": "JVM Statistics - Heaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "JVM Statistics Threads/Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  { "title": "HikariCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Connections Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 71 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 75 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Thread Config Min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 86 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "jetty_threads_config_min{instance=\"$instance\", application=\"$application\"} or tomcat_threads_config_min{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Min threads"
    }
   ]
  },
  {
   "title": "HTTP Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 86 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "5xx - Server Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"4..\"}[1m]))",
     "legendFormat": "4xx - Client Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"2..\"}[1m]))",
     "legendFormat": "2xx - Success"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"3..\"}[1m]))",
     "legendFormat": "3xx - Redirections"
    }
   ]
  },
  {
   "title": "Thread Config Max",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 90 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "jetty_threads_config_max{instance=\"$instance\", application=\"$application\"} or tomcat_threads_config_max{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Max threads"
    }
   ]
  },
  {
   "title": "Requests/second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!~\".*actuator.*\"}[1m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Requests duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "TOP 10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!~\".*actuator.*\"}[1m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jetty_threads_current{instance=\"$instance\", application=\"$application\"} or tomcat_threads_current_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Current thread"
    },
    {
     "expr": "jetty_threads_busy{instance=\"$instance\", application=\"$application\"} or tomcat_threads_busy_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Busy thread"
    },
    {
     "expr": "jetty_threads_idle{instance=\"$instance\", application=\"$application\"} or tomcat_threads_idle_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Idle threads"
    },
    {
     "expr": "jetty_threads_jobs{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Jobs  threads"
    }
   ]
  },
  { "title": "Logback Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "INFO logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"info\"}[5m])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 132 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 132 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}